Add --system and --all-logs support to bosh logs --director
cloudfoundry/bosh-cli pull request #616
Opened 2023-03-24 00:44 UTC by jpalermo

Follow on to #610 and #614

2023-03-24 17:46 UTC, klakin-pivotal requested changes

2023-03-24 21:11 UTC, jpalermo commented on director/deployment_test.go
> -		It("is correctly fetches job, agent, and system logs when --all is passed", func() {
The code in deployment no longer has this logic though. The log type is passed in as a string and just directly used. Previously the logic for determining which string to send was in the deployment, so the tests made sense here. The deleted tests are all identical to the [test that was left](https://github.com/cloudfoundry/bosh-cli/pull/616/files#diff-1c255e0d31c5bb8ffb4126a80bfe5620c98958bad4884cc8e35435bd7fe429fbR224) except for the value of the logType, and you can put whatever string value you want in there.

Now the log cmd determines what the log type should be (and the logic is shared between the two different log commands) and tests that verify it passes the correct value down to the deployment are [here](https://github.com/cloudfoundry/bosh-cli/pull/616/files#diff-22e518acf530a844ab4051bf614550b8ebfca84040fb558fab1c4fc3c2b0fed8R144), [here](https://github.com/cloudfoundry/bosh-cli/pull/616/files#diff-22e518acf530a844ab4051bf614550b8ebfca84040fb558fab1c4fc3c2b0fed8R127), [here](https://github.com/cloudfoundry/bosh-cli/pull/616/files#diff-22e518acf530a844ab4051bf614550b8ebfca84040fb558fab1c4fc3c2b0fed8R110), and [here](https://github.com/cloudfoundry/bosh-cli/pull/616/files#diff-22e518acf530a844ab4051bf614550b8ebfca84040fb558fab1c4fc3c2b0fed8R85)

2023-03-25 00:09 UTC, klakin-pivotal commented on director/deployment_test.go
> -		It("is correctly fetches job, agent, and system logs when --all is passed", func() {
I like it when the tests document the intent of the code.

So it'd be good if the tests document that either
*  when you put any and all combinations of expected values in, you get the expected values out
* _anything_ you feed to this function gets plopped into the expected place in the URI that it returns and uses in that `get` request

And if we're doing the latter, the data we feed in in the test should probably be data that requires URI-escaping... just to make sure that that part of the code works as it should.

2023-03-28 21:00 UTC, jpalermo commented on director/deployment_test.go
> -		It("is correctly fetches job, agent, and system logs when --all is passed", func() {
👍 I updated the test and assertion to include a URI escaped example

2023-03-29 17:36 UTC, klakin-pivotal commented on director/deployment_test.go
> -		It("is correctly fetches job, agent, and system logs when --all is passed", func() {
Love it.

2023-03-29 17:37 UTC, klakin-pivotal approved these changes

2023-03-29 20:58 UTC, merged